[Fixed] commands

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -22,7 +22,7 @@ jobs:
         run: |
           npm install
 
-      - name: Save key file to EC2
+      - name: Deploy to EC2
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -33,14 +33,18 @@ jobs:
           echo "$SSH_KEY" > /tmp/my-key.pem
           chmod 600 /tmp/my-key.pem
 
-      - name: Copy Files to EC2
-        run: |
-          scp -i /tmp/my-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* ec2-user@$INSTANCE_IP:/root/backend
 
-      - name: Deploy Node.js Backend
-        run: |
+          # Check if the build directory exists before transferring
+          if [ -d "./packages/api-gateway" ]; then
+            # Transfer files to the EC2 instance
+            scp -o StrictHostKeyChecking=no -i /tmp/my-key.pem -r ./* ec2-user@$INSTANCE_IP:/root/backend
+          else
+            echo "Directory not found!"
+            exit 1  # Exit with an error if the build directory does not exist
+          fi
+
+          # SSH into EC2 and restart the backend server
           ssh -i /tmp/my-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@$INSTANCE_IP "cd /root/backend && npm install && pm2 restart my-backend-app || pm2 start app.js --name my-backend-app"
 
-      - name: Clean Up
-        run: |
+          # Cleanup
           rm -f /tmp/my-key.pem
